# Import Packages

In [5]:
import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
from sklearn.model_selection import train_test_split
from sklearn import metrics

# Data Preprocessing

In [8]:
##讀檔:可用自己習慣的方式讀檔
from google.colab import files
data = files.upload()

Saving Heart Failure Clinical Records.csv to Heart Failure Clinical Records.csv

In [9]:
# Read file
path = '/content/Heart Failure Clinical Records.csv'
data = pd.read_csv(path)

In [10]:
# Drop Label on X
X = data.drop(['time', 'DEATH_EVENT'], axis=1).copy()
X

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0
...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,143,1,1
295,55.0,0,1820,0,38,0,270000.00,1.2,139,0,0
296,45.0,0,2060,1,60,0,742000.00,0.8,138,0,0
297,45.0,0,2413,0,38,0,140000.00,1.4,140,1,1
298,50.0,0,196,0,45,0,395000.00,1.6,136,1,1

In [11]:
# Assign target
y = data['DEATH_EVENT'].copy()
y

0      1
1      1
2      1
3      1
4      1
      ..
294    0
295    0
296    0
297    0
298    0
Name: DEATH_EVENT, Length: 299, dtype: int64

In [25]:
# Splitting into train and test (test_size=0.25, random_state=2)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=2)

# Train

In [26]:
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn import neighbors
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)

xgb_model = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
xgb_model.fit(X_train, y_train)

dt_model = DecisionTreeClassifier(random_state=2)
dt_model.fit(X_train, y_train)

rf_model = RandomForestClassifier(random_state=2)
rf_model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [07:01:16] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

RandomForestClassifier(random_state=2)

# Prediction

In [30]:
lr_pred = lr_model.predict(X_test)
xgb_pred = xgb_model.predict(X_test)
dt_pred = dt_model.predict(X_test)
rf_pred = rf_model.predict(X_test)

print(lr_pred)

[0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0
 0]

# F1_Score

In [31]:
from sklearn.metrics import f1_score
print("LogisticRegression F1-Score:", f1_score(y_test, lr_pred))
print("XGBoost F1-Score:", f1_score(y_test, xgb_pred))
print("Decision Tree F1-Score:", f1_score(y_test, dt_pred))
print("RandomForest F1-Score:", f1_score(y_test, rf_pred))

LogisticRegression F1-Score: 0.5294117647058824
XGBoost F1-Score: 0.5333333333333333
Decision Tree F1-Score: 0.46511627906976744
RandomForest F1-Score: 0.5789473684210527